scope: knb-lter-cap
identifier: 46
baseURL: https://gios-data.s3.us-west-2.amazonaws.com/datasets/cap/
project: lter
title: "Point-count bird censusing: long-term monitoring of bird abundance and diversity in central Arizona-Phoenix, ongoing since 2000"
maintenance: regular
geographic_description: 'CAP LTER study area: greater Phoenix, Arizona (USA) metropolitan area and surrounding Sonoran desert region'
