---
title: "knb-lter-46_abstract"
output: md_document
---

# project overview

Over the past half-century, the greater Phoenix metropolitan area (GPMA) has been one of the fastest growing regions in the US, experiencing rapid urban expansion in addition to urban intensification. This backdrop provides an ideal setting to monitor biodiversity changes in response to urbanization, and the CAP LTER has been using a standardized point-count protocol to monitor the bird community in the GPMA and surrounding Sonoran desert region since 2000. 

The bird survey locations in this CAP LTER core monitoring program include six general site groupings:

1. ESCA. Forty bird survey locations were selected from a subset of the CAP LTER's Ecological Survey of Central Arizona (ESCA; formerly named Survey200) long-term monitoring sites. ESCA sites were located using a tessellation-stratified dual-density sampling design, and, as such, span a diversity of habitats including urban, suburban, rural, commercial areas, parks, agricultural fields, and native Sonoran desert. Earlier versions of this data package included data from the ESCA project that was intended to complement the bird data. However, while positioned in close proximity, the bird survey locations do not necessarily overlap with the 30m x 30m plot that constitutes an ESCA sampling location, and leveraging data from these two monitoring programs should be addressed carefully. ESCA data have corresponding survey location names, and those data are available through the CAP LTER and LTER network data portals. At the conclusion of the 2016 spring survey, fifteen of the ESCA-correlated sites were discontinued as the core monitoring program refocused its efforts on desert parks and PASS neighborhoods. Among the deleted locations were all agricultural and commercial sites, as well as sites where access had become restrictive. 

2. North Desert Village (NDV). Additional bird survey locations were positioned in treatment areas of the North Desert Village (NDV). This was a site of intense study on the Arizona State University Polytechnic Campus in which the CAP LTER converted the landscaping of small neighborhoods to reflect the dominant landscaping preferences employed throughout the GPMA. NDV landscape types include: oasis (NDV-O), xeric (NDV-X), mesic (NDV-M), control (NDV-C), and native (NDV-N). Monitoring at NDV was discontinued after the spring 2016 season as research efforts at this site came to an end.

3. Riparian. While the forty bird survey locations that were selected to coincide with ESCA sampling locations span a wide diversity of habitats throughout the GPMA, because of the generally random nature of selecting those sites, they did not reflect riparian habitats. Riparian areas are important bird habitat but constitute a very small area of the GPMA. To address this deficiency, bird survey locations were established specifically in twelve riparian habitats. Riparian habitat sub-types include: (1) ephemeral-engineered (EE, n=4), (2) ephemeral-natural (EN, n=2), (3) perennial-engineered (PE, n=3), and (4) perennial-natural (PN, n=3). This research was successfully concluded and these sites were discontinued after the spring 2016 season.

4. Salt River. Seven study sites along the Salt River as it runs through the GPMA that were selected as part of a related study (Salt River Biodiversity Project (SRBP)) were ultimately included in the CAP LTER's core bird monitoring programs. These sites reflect continued monitoring of riparian habitat.

5. Desert Fertilization. Beginning with the 2016-2017 winter survey, six sites at desert parks were added to core monitoring to coincide with the CAP LTER Desert Fertilization (DesFert) experiment sites. 

6. PASS. Beginning with the 2016-2017 winter survey, what used to be a separate bird-monitoring effort (monitoring in Phoenix Area Social Survey (PASS) neighborhoods) was incorporated into this core bird-monitoring program. Eight points were carried over from prior PASS monitoring, and 28 new points established, resulting in three bird monitoring locations in each of the twelve PASS neighborhoods. Visiting these locations each year, versus only in years surrounding the PASS survey as done previously, provides more data on bird populations found in the neighborhoods of the CAP LTER study area.

# method overview

In a given season, each bird survey location is visited independently by three birders who count all birds seen or heard within a 15-minute window. The frequency of surveys has varied through the life of the project. The first year of the project (2000) was generally a pilot year in which each site was visited approximately twice by a varying number of birders. The monitoring became more formalized beginning in 2001, and each site was visited in each of four seasons by three birders. The frequency of visits was reduced to three seasons in 2005, and to two season (spring, winter) beginning in 2006. 